# Prometheus Configuration for DAAP
# Coleta métricas dos 3 serviços principais a cada 15 segundos

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'daap-monitor'
    environment: 'development'

# Scrape configurations
scrape_configs:
  # Reviews Service
  - job_name: 'reviews-service'
    static_configs:
      - targets: ['reviews-service:9464']
        labels:
          service: 'reviews-service'
          tier: 'api'

  # Cache Service
  - job_name: 'cache-service'
    static_configs:
      - targets: ['cache-service:9464']
        labels:
          service: 'cache-service'
          tier: 'cache'

  # Search Service
  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:9464']
        labels:
          service: 'search-service'
          tier: 'search'

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
