config:
  target: 'http://reviews.localhost'
  phases:
    # Warm-up phase
    - duration: 30
      arrivalRate: 5
      name: "Warm-up"
    
    # Ramp-up phase
    - duration: 60
      arrivalRate: 10
      rampTo: 50
      name: "Ramp-up"
    
    # Sustained load phase
    - duration: 300
      arrivalRate: 50
      name: "Sustained load"
    
    # Peak load phase
    - duration: 120
      arrivalRate: 100
      name: "Peak load"
    
    # Cool-down phase
    - duration: 60
      arrivalRate: 100
      rampTo: 5
      name: "Cool-down"

  payload:
    # This will be dynamically replaced by the load test script
    path: './queries.csv'
    fields:
      - query
    cast: false
    order: random

  plugins:
    metrics-by-endpoint:
      useOnlyRequestNames: true

  processor: './artillery-processor.js'

scenarios:
  - name: "Search Performance Test"
    weight: 80
    flow:
      - get:
          url: "/api/reviews/search?q={{ query }}"
          name: "search"
          capture:
            - json: "$.length"
              as: "resultCount"
            - header: "x-cache-status"
              as: "cacheStatus"
          think: 1

  - name: "Cache Hit Test"
    weight: 15
    flow:
      # First request (likely cache miss)
      - get:
          url: "/api/reviews/search?q=excellent"
          name: "cache_miss"
      
      # Immediate second request (should be cache hit)
      - get:
          url: "/api/reviews/search?q=excellent"
          name: "cache_hit"

  - name: "Health Check"
    weight: 5
    flow:
      - get:
          url: "/health"
          name: "health"

  - name: "Cache Service Direct"
    weight: 10
    flow:
      - get:
          url: "/api/cache/search?q={{ query }}"
          name: "cache_direct"

# Custom metrics
metrics:
  - name: "cache_hit_ratio"
    expression: "rate(cache_hit) / rate(search)"
  
  - name: "avg_search_time"
    expression: "avg(search.response_time)"

# Reporting
reporting:
  output:
    - type: json
      path: "./artillery-results.json"
    - type: html
      path: "./artillery-report.html"
